global:
  resolve_timeout: 1m
  slack_api_url: '${SLACK_WEBHOOK_URL_INFRASTRUCTURE_ALERTS_0}'

route:
  receiver: slack
  group_by:
  - alertname
  - env
  routes:
  - receiver: slack
    match:
      severity: p0_critical|p1_minor|p2_major
    continue: true

receivers:
- name: slack
  slack_configs:
  - channel: '#infrastructure-alerts'
    send_resolved: true
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for .{{ .CommonLabels.env }} env
    text: >-
     {{ range .Alerts -}}
     *Alert:* {{ .Annotations.summary }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Description:* {{ .Annotations.description }}

     *Details:*
       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
     {{ end }}
    icon_emoji: '{{ if ne .Status "firing" }}:white_check_mark:{ else if eq .CommonLabels.severity "p0_critical" }}:no_entry_sign:{{ else if eq .CommonLabels.severity "p1_major" }}:fire:{{ else if eq .CommonLabels.severity "p2_minor" }}:warning:{{ end }}'
    color: '{{ if ne .Status "firing" }}#08990f{{ else if eq .CommonLabels.severity "p0_critical" }}#db0b0b{{ else if eq .CommonLabels.severity "p1_major" }}#e2833f{{ else if eq .CommonLabels.severity "p2_minor" }}#eddc24{{ end }}'
    username: '{{ if ne .Status "firing" }}Resolved{{ else if eq .CommonLabels.severity "p0_critical" }}Critical{{ else if eq .CommonLabels.severity "p1_major" }}Major{{ else if eq .CommonLabels.severity "p2_minor" }}Warning{{ end }}'
